# -- !Ups

-- To ensure UUIDs are autogenerated
create extension if not exists "uuid-ossp";

-- Constraint tables
create table fcm_devices (
    registration_token varchar not null constraint pk_fcm_devices primary key,
    user_id uuid not null,
    manufacturer varchar not null,
    model varchar not null,
    is_physical_device boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

# -- !Downs