apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: notification
  labels:
    app: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        # Sidecar container for cloudsql-proxy to connect to CloudSql database - recommended approach by Google for GKE
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
          command:
            - /cloud_sql_proxy
            - -instances=fitcentive-dev-02:northamerica-northeast2:gke-dev-env-cloud-sql-instance:=tcp:5432
            - -credential_file=/secrets/cloudsql/credentials.json
          volumeMounts:
            - name: cloudsql-creds
              mountPath: /secrets/cloudsql
              readOnly: true
        - name: notification-service
          image: gcr.io/fitcentive-dev-02/notification:1.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: 500Mi
              cpu: "0.1"
            limits:
              memory: 800Mi
              cpu: "0.5"
          ports:
            - name: http-port
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /api/notification/healthz
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/notification/health
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 15
          envFrom:
            - secretRef:
                name: internal-service-secret
            - secretRef:
                name: notification-service-service-account-credentials
            - secretRef:
                name: notification-service-cloudsql-database-credentials
            - secretRef:
                name: firebase-admin-service-account-credentials
          env:
            - name: GCP_PROJECT_NAME
              value: "fitcentive-dev-02"
            - name: DB_HOST
              value: "localhost"
            - name: DB_PORT
              value: "5432"
#            - name: SMTP_HOST
#              value: "mailhog-service.mailhog"
#            - name: SMTP_PORT
#              value: "1025"
#            - name: SMTP_USER
#              value: ""
#            - name: SMTP_PASSWORD
#              value: ""
            - name: SMTP_HOST
              value: "in-v3.mailjet.com"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USER
              # This value is the API key from mailjet - https://app.mailjet.com/account/relay
              value: "c97324bd1ac6e563eef5424c278d5d05"
              # This value is the associated secret with the API key above - https://app.mailjet.com/account/relay
            - name: SMTP_PASSWORD
              value: "e6d38f5fedb15725a7e89db05fd7b32c"
            - name: RUNTIME_ENVIRONMENT
              value: "gke-dev-env"
            - name: TOPIC_EMAIL_VERIFICATION_TOKEN_CREATED
              value: "email-verification-token-created"
            - name: SUBSCRIPTION_EMAIL_VERIFICATION_TOKEN_CREATED
              value: "email-verification-token-created"
            - name: TOPIC_USER_COMMENTED_ON_POST
              value: "user-commented-on-post"
            - name: TOPIC_USER_LIKED_POST
              value: "user-liked-post"
            - name: TOPIC_CHAT_ROOM_MESSAGE_SENT
              value: "chat-room-message-sent"
            - name: TOPIC_USER_FRIEND_REQUESTED
              value: "user-friend-requested"
            - name: TOPIC_USER_FRIEND_REQUEST_DECISION
              value: "user-friend-request-decision"
            - name: TOPIC_PARTICIPANT_ADDED_TO_MEETUP
              value: "participant-added-to-meetup"
            - name: TOPIC_PARTICIPANT_ADDED_AVAILABILITY_TO_MEETUP
              value: "participant-added-availability-to-meetup"
            - name: TOPIC_MEETUP_DECISION
              value: "meetup-decision"
            - name: TOPIC_MEETUP_REMINDER
              value: "meetup-reminder"
            - name: TOPIC_MEETUP_LOCATION_CHANGED
              value: "meetup-location-changed"
            - name: SUBSCRIPTION_CHAT_ROOM_MESSAGE_SENT
              value: "chat-room-message-sent"
            - name: SUBSCRIPTION_USER_FRIEND_REQUESTED
              value: "user-friend-requested"
            - name: SUBSCRIPTION_USER_FRIEND_REQUEST_DECISION
              value: "user-friend-request-decision"
            - name: SUBSCRIPTION_USER_COMMENTED_ON_POST
              value: "user-commented-on-post"
            - name: SUBSCRIPTION_USER_LIKED_POST
              value: "user-liked-post"
            - name: SUBSCRIPTION_PARTICIPANT_ADDED_TO_MEETUP
              value: "participant-added-to-meetup"
            - name: SUBSCRIPTION_PARTICIPANT_ADDED_AVAILABILITY_TO_MEETUP
              value: "participant-added-availability-to-meetup"
            - name: SUBSCRIPTION_MEETUP_DECISION
              value: "meetup-decision"
            - name: SUBSCRIPTION_MEETUP_REMINDER
              value: "meetup-reminder"
            - name: SUBSCRIPTION_MEETUP_LOCATION_CHANGED
              value: "meetup-location-changed"
            - name: JWT_ISSUER
              value: "https://auth.fitcentive.xyz"
            - name: KEYCLOAK_SERVER_URL
              value: "http://keycloak-service-http.keycloak/auth"
            - name: USER_SERVICE_HOST
              value: "http://user-service.user"
            - name: USER_SERVICE_PORT
              value: "9000"
            - name: IMAGE_HOST_BASE_URL
              value: "https://api.fitcentive.xyz/api/gateway/image"
      volumes:
        - name: cloudsql-creds
          secret:
            secretName: notification-service-cloudsql-instance-credentials