apiVersion: batch/v1
kind: CronJob
metadata:
  name: flush-stale-notifications-cronjob
  namespace: notification
spec:
  # This runs every 6 hours
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: flush-stale-notifications-cronjob
              image: gcr.io/fitcentive-dev-03/gcloud-notification-cron-pubsub-image:1.0
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /opt/service-account
                  name: service-account
          restartPolicy: OnFailure
          volumes:
            - name: service-account
              configMap:
                name: notification-service-service-account