apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification:1.0
          imagePullPolicy: Never
          resources:
            requests:
              memory: 300Mi
              cpu: "0.5"
            limits:
              memory: 500Mi
              cpu: "1.0"
          ports:
            - name: http-port
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /api/notification/health
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/notification/health
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 15
          env:
            - name: GCP_PROJECT_NAME
              value: "fitcentive-1210"
            - name: SMTP_HOST
              value: "mailhog"
            - name: SMTP_PORT
              value: "1025"
            - name: SMTP_USER
              value: ""
            - name: SMTP_PASSWORD
              value: ""
            - name: RUNTIME_ENVIRONMENT
              value: "local"
