apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification:1.0
          imagePullPolicy: Never
          resources:
            requests:
              memory: 300Mi
              cpu: "0.5"
            limits:
              memory: 500Mi
              cpu: "1.0"
          ports:
            - name: http-port
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /api/notification/health
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/notification/health
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 15
          env:
            - name: GCP_PROJECT_NAME
              value: "fitcentive-1210"
            - name: DB_HOST
              # host.minikube.internal resolved IP
              value: "192.168.64.3"
            - name: DB_PORT
              value: "1211"
            - name: DB_DATABASE
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: SMTP_HOST
              value: "mailhog"
            - name: SMTP_PORT
              value: "1025"
            - name: SMTP_USER
              value: ""
            - name: SMTP_PASSWORD
              value: ""
            - name: RUNTIME_ENVIRONMENT
              value: "local"
            - name: TOPIC_EMAIL_VERIFICATION_TOKEN_CREATED
              value: "email-verification-token-created"
            - name: SUBSCRIPTION_EMAIL_VERIFICATION_TOKEN_CREATED
              value: "email-verification-token-created"
            - name: TOPIC_USER_FOLLOW_REQUESTED
              value: "user-follow-requested"
            - name: TOPIC_USER_FOLLOW_REQUEST_DECISION
              value: "user-follow-request-decision"
            - name: SUBSCRIPTION_USER_FOLLOW_REQUESTED
              value: "user-follow-requested"
            - name: SUBSCRIPTION_USER_FOLLOW_REQUEST_DECISION
              value: "user-follow-request-decision"
            - name: INTERNAL_SERVICE_SECRET
              value: "ymmtuBE62NJRIro6eCBxl5wcIZvmKg3nSTgP2YSyjOB5fq3S0ZNFXdY1DLUBo8ji"
            - name: JWT_ISSUER
              value: "http://api.vid.app"
            - name: KEYCLOAK_SERVER_URL
              value: "http://auth-keycloak-http/auth"
